site_name: ULHPC Demonstrators
nav:
  ##########
#  - General:
  - Home: 'index.md'
  - Demonstrators:
      - Digital Twin of a Biomass Furnace: 'biomass/index.md'
      - Co-located Partitioning for Multi-Physics Coupled Simulations: 'ColocatedMultiPhysics/index.md'
      - Hybrid MPI+OpenMP Parallelization for DEM: 'hydridDEM/index.md'
      - Transition to Green Hydrogen in Steel Making: 'steelmaking/index.md'
   ##############
  - Web Portals:
    - Uni.lu HPC (ULHPC): https://hpc.uni.lu
    - Technical Documentation: https://hpc-docs.uni.lu
    - Live Platform status: https://hpc.uni.lu/live-status/motd
    - ULHPC Tutorials: https://ulhpc-tutorials.readthedocs.io/
    - Helpdesk / Ticket Portal: https://hpc.uni.lu/support
    - National Competence Centre (NCC) in HPC: https://www.luxinnovation.lu/national-competence-centre-in-hpc
  - Contributing:
    - Overview: 'contributing/index.md'
    - Repository Layout: 'layout.md'
    - Pre-Requisites and Repository Setup: 'setup.md'
    - Semantic Versioning: 'contributing/versioning.md'

# Project Information
site_name: ULHPC Demonstrators
site_description: ULHPC Demonstrators
site_author: L. Koutsantonis, S. Varrette, and Uni.lu HPC (ULHPC) Team
site_dir: public
site_url: "https://hpc-demos.uni.lu/"

# Repository
repo_name: www/ulhpc-demos
repo_url: https://gitlab.uni.lu/www/ulhpc-demos
#edit_uri: blob/master/docs/

# Copyright
copyright: Copyright &copy; 2020-2021 L. Koutsantonis, F. Pinel, S. Varrette and Uni.lu HPC (ULHPC) Team

# Configuration
# strict: true

theme:
  name: material
  logo: images/logo_ULHPC_square.jpg
  language: en
  palette:
    primary: blue
    accent:  light blue
  features:
    - navigation.expand
    - navigation.top

plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: date
  - progress
  - include-markdown

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ULHPC
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.uni.lu/ULHPC
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ULHPC

# Extra stylesheets (incl. Twitter Bootstrap)
extra_css:
  - stylesheets/extra.css
  # - stylesheets/bootstrap.min.css

# Extra javascript
extra_javascript:
  - javascripts/extra.js
  - javascripts/bootstrap.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js
  # https://squidfunk.github.io/mkdocs-material/reference/data-tables/#sortable-tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

# Extensions
markdown_extensions:
  - attr_list
  # notes, warnings, hints, ...
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - markdown_include.include:
      base_path: docs
  - markdown.extensions.admonition
  - meta
  - pymdownx.arithmatex
  - pymdownx.details
  # Icons from Emoji extensions, giving access to following icon sets:
  # - Material Design: https://materialdesignicons.com/
  # - FontAwesome:     https://fontawesome.com/icons?d=gallery&m=free
  # – Octicons:        https://octicons.github.com/
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # auto-link HTML, FTP, and email links
  - pymdownx.magiclink:
      repo_url_shorthand: true
      social_url_shorthand: true
  - pymdownx.snippets:
      base_path: snippets
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  # code blocks with syntax highlighting, graphs
  - pymdownx.superfences
  - toc:
      permalink: true
